### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [gzc/leetcode#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by gzc** [comment]
Thanks a lot. I will choose one right now.

**Comment by karan** [comment]
Sweet thanks
